// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faber-numeris/luciole-auth/authn/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// SendConfirmationEmail provides a mock function with given fields: ctx, userConfirmation
func (_m *MockMailer) SendConfirmationEmail(ctx context.Context, userConfirmation domain.UserConfirmation) error {
	ret := _m.Called(ctx, userConfirmation)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmationEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserConfirmation) error); ok {
		r0 = rf(ctx, userConfirmation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendConfirmationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConfirmationEmail'
type MockMailer_SendConfirmationEmail_Call struct {
	*mock.Call
}

// SendConfirmationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userConfirmation domain.UserConfirmation
func (_e *MockMailer_Expecter) SendConfirmationEmail(ctx interface{}, userConfirmation interface{}) *MockMailer_SendConfirmationEmail_Call {
	return &MockMailer_SendConfirmationEmail_Call{Call: _e.mock.On("SendConfirmationEmail", ctx, userConfirmation)}
}

func (_c *MockMailer_SendConfirmationEmail_Call) Run(run func(ctx context.Context, userConfirmation domain.UserConfirmation)) *MockMailer_SendConfirmationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserConfirmation))
	})
	return _c
}

func (_c *MockMailer_SendConfirmationEmail_Call) Return(_a0 error) *MockMailer_SendConfirmationEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendConfirmationEmail_Call) RunAndReturn(run func(context.Context, domain.UserConfirmation) error) *MockMailer_SendConfirmationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
