// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/faber-numeris/luciole-auth/authn/internal/adapters/postgres/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// ConfirmUserRegistration provides a mock function with given fields: ctx, userid
func (_m *MockQuerier) ConfirmUserRegistration(ctx context.Context, userid string) error {
	ret := _m.Called(ctx, userid)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUserRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_ConfirmUserRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUserRegistration'
type MockQuerier_ConfirmUserRegistration_Call struct {
	*mock.Call
}

// ConfirmUserRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - userid string
func (_e *MockQuerier_Expecter) ConfirmUserRegistration(ctx interface{}, userid interface{}) *MockQuerier_ConfirmUserRegistration_Call {
	return &MockQuerier_ConfirmUserRegistration_Call{Call: _e.mock.On("ConfirmUserRegistration", ctx, userid)}
}

func (_c *MockQuerier_ConfirmUserRegistration_Call) Run(run func(ctx context.Context, userid string)) *MockQuerier_ConfirmUserRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_ConfirmUserRegistration_Call) Return(_a0 error) *MockQuerier_ConfirmUserRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_ConfirmUserRegistration_Call) RunAndReturn(run func(context.Context, string) error) *MockQuerier_ConfirmUserRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUser(ctx context.Context, arg gen.CreateUserParams) (gen.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 gen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.CreateUserParams) (gen.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.CreateUserParams) gen.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gen.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg gen.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.CreateUserParams))
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(_a0 gen.User, _a1 error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(context.Context, gen.CreateUserParams) (gen.User, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserConfirmation provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUserConfirmation(ctx context.Context, arg gen.CreateUserConfirmationParams) (gen.UserConfirmation, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserConfirmation")
	}

	var r0 gen.UserConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.CreateUserConfirmationParams) (gen.UserConfirmation, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.CreateUserConfirmationParams) gen.UserConfirmation); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gen.UserConfirmation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.CreateUserConfirmationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateUserConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserConfirmation'
type MockQuerier_CreateUserConfirmation_Call struct {
	*mock.Call
}

// CreateUserConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gen.CreateUserConfirmationParams
func (_e *MockQuerier_Expecter) CreateUserConfirmation(ctx interface{}, arg interface{}) *MockQuerier_CreateUserConfirmation_Call {
	return &MockQuerier_CreateUserConfirmation_Call{Call: _e.mock.On("CreateUserConfirmation", ctx, arg)}
}

func (_c *MockQuerier_CreateUserConfirmation_Call) Run(run func(ctx context.Context, arg gen.CreateUserConfirmationParams)) *MockQuerier_CreateUserConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.CreateUserConfirmationParams))
	})
	return _c
}

func (_c *MockQuerier_CreateUserConfirmation_Call) Return(_a0 gen.UserConfirmation, _a1 error) *MockQuerier_CreateUserConfirmation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateUserConfirmation_Call) RunAndReturn(run func(context.Context, gen.CreateUserConfirmationParams) (gen.UserConfirmation, error)) *MockQuerier_CreateUserConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredUserConfirmations provides a mock function with given fields: ctx
func (_m *MockQuerier) DeleteExpiredUserConfirmations(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredUserConfirmations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteExpiredUserConfirmations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredUserConfirmations'
type MockQuerier_DeleteExpiredUserConfirmations_Call struct {
	*mock.Call
}

// DeleteExpiredUserConfirmations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) DeleteExpiredUserConfirmations(ctx interface{}) *MockQuerier_DeleteExpiredUserConfirmations_Call {
	return &MockQuerier_DeleteExpiredUserConfirmations_Call{Call: _e.mock.On("DeleteExpiredUserConfirmations", ctx)}
}

func (_c *MockQuerier_DeleteExpiredUserConfirmations_Call) Run(run func(ctx context.Context)) *MockQuerier_DeleteExpiredUserConfirmations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_DeleteExpiredUserConfirmations_Call) Return(_a0 error) *MockQuerier_DeleteExpiredUserConfirmations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteExpiredUserConfirmations_Call) RunAndReturn(run func(context.Context) error) *MockQuerier_DeleteExpiredUserConfirmations_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeleteUser(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockQuerier_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQuerier_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockQuerier_DeleteUser_Call {
	return &MockQuerier_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockQuerier_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *MockQuerier_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_DeleteUser_Call) Return(_a0 error) *MockQuerier_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *MockQuerier_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserConfirmation provides a mock function with given fields: ctx, userid
func (_m *MockQuerier) DeleteUserConfirmation(ctx context.Context, userid string) error {
	ret := _m.Called(ctx, userid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteUserConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserConfirmation'
type MockQuerier_DeleteUserConfirmation_Call struct {
	*mock.Call
}

// DeleteUserConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - userid string
func (_e *MockQuerier_Expecter) DeleteUserConfirmation(ctx interface{}, userid interface{}) *MockQuerier_DeleteUserConfirmation_Call {
	return &MockQuerier_DeleteUserConfirmation_Call{Call: _e.mock.On("DeleteUserConfirmation", ctx, userid)}
}

func (_c *MockQuerier_DeleteUserConfirmation_Call) Run(run func(ctx context.Context, userid string)) *MockQuerier_DeleteUserConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_DeleteUserConfirmation_Call) Return(_a0 error) *MockQuerier_DeleteUserConfirmation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteUserConfirmation_Call) RunAndReturn(run func(context.Context, string) error) *MockQuerier_DeleteUserConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetUser(ctx context.Context, id string) (gen.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 gen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (gen.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) gen.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(gen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockQuerier_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQuerier_Expecter) GetUser(ctx interface{}, id interface{}) *MockQuerier_GetUser_Call {
	return &MockQuerier_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockQuerier_GetUser_Call) Run(run func(ctx context.Context, id string)) *MockQuerier_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUser_Call) Return(_a0 gen.User, _a1 error) *MockQuerier_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUser_Call) RunAndReturn(run func(context.Context, string) (gen.User, error)) *MockQuerier_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (gen.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 gen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (gen.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) gen.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(gen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockQuerier_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockQuerier_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockQuerier_GetUserByEmail_Call {
	return &MockQuerier_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockQuerier_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) Return(_a0 gen.User, _a1 error) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (gen.User, error)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserConfirmationByToken provides a mock function with given fields: ctx, token
func (_m *MockQuerier) GetUserConfirmationByToken(ctx context.Context, token string) (gen.UserConfirmation, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserConfirmationByToken")
	}

	var r0 gen.UserConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (gen.UserConfirmation, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) gen.UserConfirmation); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(gen.UserConfirmation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserConfirmationByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserConfirmationByToken'
type MockQuerier_GetUserConfirmationByToken_Call struct {
	*mock.Call
}

// GetUserConfirmationByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockQuerier_Expecter) GetUserConfirmationByToken(ctx interface{}, token interface{}) *MockQuerier_GetUserConfirmationByToken_Call {
	return &MockQuerier_GetUserConfirmationByToken_Call{Call: _e.mock.On("GetUserConfirmationByToken", ctx, token)}
}

func (_c *MockQuerier_GetUserConfirmationByToken_Call) Run(run func(ctx context.Context, token string)) *MockQuerier_GetUserConfirmationByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUserConfirmationByToken_Call) Return(_a0 gen.UserConfirmation, _a1 error) *MockQuerier_GetUserConfirmationByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserConfirmationByToken_Call) RunAndReturn(run func(context.Context, string) (gen.UserConfirmation, error)) *MockQuerier_GetUserConfirmationByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserConfirmationByUserID provides a mock function with given fields: ctx, userid
func (_m *MockQuerier) GetUserConfirmationByUserID(ctx context.Context, userid string) (gen.UserConfirmation, error) {
	ret := _m.Called(ctx, userid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserConfirmationByUserID")
	}

	var r0 gen.UserConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (gen.UserConfirmation, error)); ok {
		return rf(ctx, userid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) gen.UserConfirmation); ok {
		r0 = rf(ctx, userid)
	} else {
		r0 = ret.Get(0).(gen.UserConfirmation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserConfirmationByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserConfirmationByUserID'
type MockQuerier_GetUserConfirmationByUserID_Call struct {
	*mock.Call
}

// GetUserConfirmationByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userid string
func (_e *MockQuerier_Expecter) GetUserConfirmationByUserID(ctx interface{}, userid interface{}) *MockQuerier_GetUserConfirmationByUserID_Call {
	return &MockQuerier_GetUserConfirmationByUserID_Call{Call: _e.mock.On("GetUserConfirmationByUserID", ctx, userid)}
}

func (_c *MockQuerier_GetUserConfirmationByUserID_Call) Run(run func(ctx context.Context, userid string)) *MockQuerier_GetUserConfirmationByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUserConfirmationByUserID_Call) Return(_a0 gen.UserConfirmation, _a1 error) *MockQuerier_GetUserConfirmationByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserConfirmationByUserID_Call) RunAndReturn(run func(context.Context, string) (gen.UserConfirmation, error)) *MockQuerier_GetUserConfirmationByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListUsers(ctx context.Context, arg gen.ListUsersParams) ([]gen.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []gen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.ListUsersParams) ([]gen.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.ListUsersParams) []gen.User); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gen.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.ListUsersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockQuerier_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gen.ListUsersParams
func (_e *MockQuerier_Expecter) ListUsers(ctx interface{}, arg interface{}) *MockQuerier_ListUsers_Call {
	return &MockQuerier_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, arg)}
}

func (_c *MockQuerier_ListUsers_Call) Run(run func(ctx context.Context, arg gen.ListUsersParams)) *MockQuerier_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.ListUsersParams))
	})
	return _c
}

func (_c *MockQuerier_ListUsers_Call) Return(_a0 []gen.User, _a1 error) *MockQuerier_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListUsers_Call) RunAndReturn(run func(context.Context, gen.ListUsersParams) ([]gen.User, error)) *MockQuerier_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdatePassword(ctx context.Context, arg gen.UpdatePasswordParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.UpdatePasswordParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockQuerier_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gen.UpdatePasswordParams
func (_e *MockQuerier_Expecter) UpdatePassword(ctx interface{}, arg interface{}) *MockQuerier_UpdatePassword_Call {
	return &MockQuerier_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, arg)}
}

func (_c *MockQuerier_UpdatePassword_Call) Run(run func(ctx context.Context, arg gen.UpdatePasswordParams)) *MockQuerier_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.UpdatePasswordParams))
	})
	return _c
}

func (_c *MockQuerier_UpdatePassword_Call) Return(_a0 error) *MockQuerier_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_UpdatePassword_Call) RunAndReturn(run func(context.Context, gen.UpdatePasswordParams) error) *MockQuerier_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUser(ctx context.Context, arg gen.UpdateUserParams) (gen.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 gen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.UpdateUserParams) (gen.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.UpdateUserParams) gen.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockQuerier_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gen.UpdateUserParams
func (_e *MockQuerier_Expecter) UpdateUser(ctx interface{}, arg interface{}) *MockQuerier_UpdateUser_Call {
	return &MockQuerier_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, arg)}
}

func (_c *MockQuerier_UpdateUser_Call) Run(run func(ctx context.Context, arg gen.UpdateUserParams)) *MockQuerier_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.UpdateUserParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateUser_Call) Return(_a0 gen.User, _a1 error) *MockQuerier_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateUser_Call) RunAndReturn(run func(context.Context, gen.UpdateUserParams) (gen.User, error)) *MockQuerier_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
