// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIServiceConfig is an autogenerated mock type for the IServiceConfig type
type MockIServiceConfig struct {
	mock.Mock
}

type MockIServiceConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServiceConfig) EXPECT() *MockIServiceConfig_Expecter {
	return &MockIServiceConfig_Expecter{mock: &_m.Mock}
}

// AllowedOrigins provides a mock function with no fields
func (_m *MockIServiceConfig) AllowedOrigins() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllowedOrigins")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockIServiceConfig_AllowedOrigins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowedOrigins'
type MockIServiceConfig_AllowedOrigins_Call struct {
	*mock.Call
}

// AllowedOrigins is a helper method to define mock.On call
func (_e *MockIServiceConfig_Expecter) AllowedOrigins() *MockIServiceConfig_AllowedOrigins_Call {
	return &MockIServiceConfig_AllowedOrigins_Call{Call: _e.mock.On("AllowedOrigins")}
}

func (_c *MockIServiceConfig_AllowedOrigins_Call) Run(run func()) *MockIServiceConfig_AllowedOrigins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceConfig_AllowedOrigins_Call) Return(_a0 []string) *MockIServiceConfig_AllowedOrigins_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceConfig_AllowedOrigins_Call) RunAndReturn(run func() []string) *MockIServiceConfig_AllowedOrigins_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function with no fields
func (_m *MockIServiceConfig) Port() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockIServiceConfig_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type MockIServiceConfig_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *MockIServiceConfig_Expecter) Port() *MockIServiceConfig_Port_Call {
	return &MockIServiceConfig_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *MockIServiceConfig_Port_Call) Run(run func()) *MockIServiceConfig_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIServiceConfig_Port_Call) Return(_a0 int) *MockIServiceConfig_Port_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIServiceConfig_Port_Call) RunAndReturn(run func() int) *MockIServiceConfig_Port_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIServiceConfig creates a new instance of MockIServiceConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServiceConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServiceConfig {
	mock := &MockIServiceConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
