// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIDatabaseConfig is an autogenerated mock type for the IDatabaseConfig type
type MockIDatabaseConfig struct {
	mock.Mock
}

type MockIDatabaseConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabaseConfig) EXPECT() *MockIDatabaseConfig_Expecter {
	return &MockIDatabaseConfig_Expecter{mock: &_m.Mock}
}

// DBHost provides a mock function with no fields
func (_m *MockIDatabaseConfig) DBHost() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBHost")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDatabaseConfig_DBHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBHost'
type MockIDatabaseConfig_DBHost_Call struct {
	*mock.Call
}

// DBHost is a helper method to define mock.On call
func (_e *MockIDatabaseConfig_Expecter) DBHost() *MockIDatabaseConfig_DBHost_Call {
	return &MockIDatabaseConfig_DBHost_Call{Call: _e.mock.On("DBHost")}
}

func (_c *MockIDatabaseConfig_DBHost_Call) Run(run func()) *MockIDatabaseConfig_DBHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseConfig_DBHost_Call) Return(_a0 string) *MockIDatabaseConfig_DBHost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseConfig_DBHost_Call) RunAndReturn(run func() string) *MockIDatabaseConfig_DBHost_Call {
	_c.Call.Return(run)
	return _c
}

// DBName provides a mock function with no fields
func (_m *MockIDatabaseConfig) DBName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDatabaseConfig_DBName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBName'
type MockIDatabaseConfig_DBName_Call struct {
	*mock.Call
}

// DBName is a helper method to define mock.On call
func (_e *MockIDatabaseConfig_Expecter) DBName() *MockIDatabaseConfig_DBName_Call {
	return &MockIDatabaseConfig_DBName_Call{Call: _e.mock.On("DBName")}
}

func (_c *MockIDatabaseConfig_DBName_Call) Run(run func()) *MockIDatabaseConfig_DBName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseConfig_DBName_Call) Return(_a0 string) *MockIDatabaseConfig_DBName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseConfig_DBName_Call) RunAndReturn(run func() string) *MockIDatabaseConfig_DBName_Call {
	_c.Call.Return(run)
	return _c
}

// DBPassword provides a mock function with no fields
func (_m *MockIDatabaseConfig) DBPassword() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBPassword")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDatabaseConfig_DBPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBPassword'
type MockIDatabaseConfig_DBPassword_Call struct {
	*mock.Call
}

// DBPassword is a helper method to define mock.On call
func (_e *MockIDatabaseConfig_Expecter) DBPassword() *MockIDatabaseConfig_DBPassword_Call {
	return &MockIDatabaseConfig_DBPassword_Call{Call: _e.mock.On("DBPassword")}
}

func (_c *MockIDatabaseConfig_DBPassword_Call) Run(run func()) *MockIDatabaseConfig_DBPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseConfig_DBPassword_Call) Return(_a0 string) *MockIDatabaseConfig_DBPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseConfig_DBPassword_Call) RunAndReturn(run func() string) *MockIDatabaseConfig_DBPassword_Call {
	_c.Call.Return(run)
	return _c
}

// DBPort provides a mock function with no fields
func (_m *MockIDatabaseConfig) DBPort() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBPort")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockIDatabaseConfig_DBPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBPort'
type MockIDatabaseConfig_DBPort_Call struct {
	*mock.Call
}

// DBPort is a helper method to define mock.On call
func (_e *MockIDatabaseConfig_Expecter) DBPort() *MockIDatabaseConfig_DBPort_Call {
	return &MockIDatabaseConfig_DBPort_Call{Call: _e.mock.On("DBPort")}
}

func (_c *MockIDatabaseConfig_DBPort_Call) Run(run func()) *MockIDatabaseConfig_DBPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseConfig_DBPort_Call) Return(_a0 int) *MockIDatabaseConfig_DBPort_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseConfig_DBPort_Call) RunAndReturn(run func() int) *MockIDatabaseConfig_DBPort_Call {
	_c.Call.Return(run)
	return _c
}

// DBSSLMode provides a mock function with no fields
func (_m *MockIDatabaseConfig) DBSSLMode() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBSSLMode")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDatabaseConfig_DBSSLMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBSSLMode'
type MockIDatabaseConfig_DBSSLMode_Call struct {
	*mock.Call
}

// DBSSLMode is a helper method to define mock.On call
func (_e *MockIDatabaseConfig_Expecter) DBSSLMode() *MockIDatabaseConfig_DBSSLMode_Call {
	return &MockIDatabaseConfig_DBSSLMode_Call{Call: _e.mock.On("DBSSLMode")}
}

func (_c *MockIDatabaseConfig_DBSSLMode_Call) Run(run func()) *MockIDatabaseConfig_DBSSLMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseConfig_DBSSLMode_Call) Return(_a0 string) *MockIDatabaseConfig_DBSSLMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseConfig_DBSSLMode_Call) RunAndReturn(run func() string) *MockIDatabaseConfig_DBSSLMode_Call {
	_c.Call.Return(run)
	return _c
}

// DBUser provides a mock function with no fields
func (_m *MockIDatabaseConfig) DBUser() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBUser")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDatabaseConfig_DBUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBUser'
type MockIDatabaseConfig_DBUser_Call struct {
	*mock.Call
}

// DBUser is a helper method to define mock.On call
func (_e *MockIDatabaseConfig_Expecter) DBUser() *MockIDatabaseConfig_DBUser_Call {
	return &MockIDatabaseConfig_DBUser_Call{Call: _e.mock.On("DBUser")}
}

func (_c *MockIDatabaseConfig_DBUser_Call) Run(run func()) *MockIDatabaseConfig_DBUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabaseConfig_DBUser_Call) Return(_a0 string) *MockIDatabaseConfig_DBUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDatabaseConfig_DBUser_Call) RunAndReturn(run func() string) *MockIDatabaseConfig_DBUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDatabaseConfig creates a new instance of MockIDatabaseConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabaseConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabaseConfig {
	mock := &MockIDatabaseConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
