// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	app "github.com/faber-numeris/luciole-auth/authn/internal/app"

	domain "github.com/faber-numeris/luciole-auth/authn/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ConfirmUserRegistration provides a mock function with given fields: ctx, token
func (_m *MockUserService) ConfirmUserRegistration(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUserRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_ConfirmUserRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUserRegistration'
type MockUserService_ConfirmUserRegistration_Call struct {
	*mock.Call
}

// ConfirmUserRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserService_Expecter) ConfirmUserRegistration(ctx interface{}, token interface{}) *MockUserService_ConfirmUserRegistration_Call {
	return &MockUserService_ConfirmUserRegistration_Call{Call: _e.mock.On("ConfirmUserRegistration", ctx, token)}
}

func (_c *MockUserService_ConfirmUserRegistration_Call) Run(run func(ctx context.Context, token string)) *MockUserService_ConfirmUserRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_ConfirmUserRegistration_Call) Return(_a0 error) *MockUserService_ConfirmUserRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_ConfirmUserRegistration_Call) RunAndReturn(run func(context.Context, string) error) *MockUserService_ConfirmUserRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *MockUserService) DeleteUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserService_Expecter) DeleteUser(ctx interface{}, userID interface{}) *MockUserService_DeleteUser_Call {
	return &MockUserService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *MockUserService_DeleteUser_Call) Run(run func(ctx context.Context, userID string)) *MockUserService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_DeleteUser_Call) Return(_a0 error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserService) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserService_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUserService_GetUserByEmail_Call {
	return &MockUserService_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserService_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserService) GetUserByID(ctx context.Context, id string) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, params
func (_m *MockUserService) ListUsers(ctx context.Context, params *app.ListUsersParams) ([]*domain.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *app.ListUsersParams) ([]*domain.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *app.ListUsersParams) []*domain.User); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *app.ListUsersParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - params *app.ListUsersParams
func (_e *MockUserService_Expecter) ListUsers(ctx interface{}, params interface{}) *MockUserService_ListUsers_Call {
	return &MockUserService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, params)}
}

func (_c *MockUserService_ListUsers_Call) Run(run func(ctx context.Context, params *app.ListUsersParams)) *MockUserService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.ListUsersParams))
	})
	return _c
}

func (_c *MockUserService_ListUsers_Call) Return(_a0 []*domain.User, _a1 error) *MockUserService_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_ListUsers_Call) RunAndReturn(run func(context.Context, *app.ListUsersParams) ([]*domain.User, error)) *MockUserService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, user, password
func (_m *MockUserService) RegisterUser(ctx context.Context, user *domain.User, password string) (*domain.User, error) {
	ret := _m.Called(ctx, user, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string) (*domain.User, error)); ok {
		return rf(ctx, user, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string) *domain.User); ok {
		r0 = rf(ctx, user, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, string) error); ok {
		r1 = rf(ctx, user, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - password string
func (_e *MockUserService_Expecter) RegisterUser(ctx interface{}, user interface{}, password interface{}) *MockUserService_RegisterUser_Call {
	return &MockUserService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, user, password)}
}

func (_c *MockUserService_RegisterUser_Call) Run(run func(ctx context.Context, user *domain.User, password string)) *MockUserService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_RegisterUser_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_RegisterUser_Call) RunAndReturn(run func(context.Context, *domain.User, string) (*domain.User, error)) *MockUserService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function with given fields: ctx, email
func (_m *MockUserService) RequestPasswordReset(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type MockUserService_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *MockUserService_RequestPasswordReset_Call {
	return &MockUserService_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *MockUserService_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *MockUserService_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_RequestPasswordReset_Call) Return(_a0 string, _a1 error) *MockUserService_RequestPasswordReset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUserService_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, token, newPassword
func (_m *MockUserService) ResetPassword(ctx context.Context, token string, newPassword string) error {
	ret := _m.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockUserService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *MockUserService_Expecter) ResetPassword(ctx interface{}, token interface{}, newPassword interface{}) *MockUserService_ResetPassword_Call {
	return &MockUserService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, newPassword)}
}

func (_c *MockUserService_ResetPassword_Call) Run(run func(ctx context.Context, token string, newPassword string)) *MockUserService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_ResetPassword_Call) Return(_a0 error) *MockUserService_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_ResetPassword_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function with given fields: ctx, userID, req
func (_m *MockUserService) UpdateUserProfile(ctx context.Context, userID string, req *domain.User) (*domain.User, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.User) (*domain.User, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.User) *domain.User); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.User) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type MockUserService_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *domain.User
func (_e *MockUserService_Expecter) UpdateUserProfile(ctx interface{}, userID interface{}, req interface{}) *MockUserService_UpdateUserProfile_Call {
	return &MockUserService_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", ctx, userID, req)}
}

func (_c *MockUserService_UpdateUserProfile_Call) Run(run func(ctx context.Context, userID string, req *domain.User)) *MockUserService_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*domain.User))
	})
	return _c
}

func (_c *MockUserService_UpdateUserProfile_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_UpdateUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdateUserProfile_Call) RunAndReturn(run func(context.Context, string, *domain.User) (*domain.User, error)) *MockUserService_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: ctx, email, password
func (_m *MockUserService) VerifyPassword(ctx context.Context, email string, password string) (*domain.User, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockUserService_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUserService_Expecter) VerifyPassword(ctx interface{}, email interface{}, password interface{}) *MockUserService_VerifyPassword_Call {
	return &MockUserService_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, email, password)}
}

func (_c *MockUserService_VerifyPassword_Call) Run(run func(ctx context.Context, email string, password string)) *MockUserService_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_VerifyPassword_Call) Return(_a0 *domain.User, _a1 error) *MockUserService_VerifyPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_VerifyPassword_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockUserService_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
