// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHashingService is an autogenerated mock type for the HashingService type
type MockHashingService struct {
	mock.Mock
}

type MockHashingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashingService) EXPECT() *MockHashingService_Expecter {
	return &MockHashingService_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: ctx, password
func (_m *MockHashingService) HashPassword(ctx context.Context, password []byte) ([]byte, error) {
	ret := _m.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return rf(ctx, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashingService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockHashingService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - password []byte
func (_e *MockHashingService_Expecter) HashPassword(ctx interface{}, password interface{}) *MockHashingService_HashPassword_Call {
	return &MockHashingService_HashPassword_Call{Call: _e.mock.On("HashPassword", ctx, password)}
}

func (_c *MockHashingService_HashPassword_Call) Run(run func(ctx context.Context, password []byte)) *MockHashingService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockHashingService_HashPassword_Call) Return(_a0 []byte, _a1 error) *MockHashingService_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashingService_HashPassword_Call) RunAndReturn(run func(context.Context, []byte) ([]byte, error)) *MockHashingService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHashingService creates a new instance of MockHashingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashingService {
	mock := &MockHashingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
