// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faber-numeris/luciole-auth/authn/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockUserConfirmationRepository is an autogenerated mock type for the UserConfirmationRepository type
type MockUserConfirmationRepository struct {
	mock.Mock
}

type MockUserConfirmationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserConfirmationRepository) EXPECT() *MockUserConfirmationRepository_Expecter {
	return &MockUserConfirmationRepository_Expecter{mock: &_m.Mock}
}

// ConfirmUserRegistration provides a mock function with given fields: ctx, userID
func (_m *MockUserConfirmationRepository) ConfirmUserRegistration(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUserRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserConfirmationRepository_ConfirmUserRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUserRegistration'
type MockUserConfirmationRepository_ConfirmUserRegistration_Call struct {
	*mock.Call
}

// ConfirmUserRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserConfirmationRepository_Expecter) ConfirmUserRegistration(ctx interface{}, userID interface{}) *MockUserConfirmationRepository_ConfirmUserRegistration_Call {
	return &MockUserConfirmationRepository_ConfirmUserRegistration_Call{Call: _e.mock.On("ConfirmUserRegistration", ctx, userID)}
}

func (_c *MockUserConfirmationRepository_ConfirmUserRegistration_Call) Run(run func(ctx context.Context, userID string)) *MockUserConfirmationRepository_ConfirmUserRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserConfirmationRepository_ConfirmUserRegistration_Call) Return(_a0 error) *MockUserConfirmationRepository_ConfirmUserRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserConfirmationRepository_ConfirmUserRegistration_Call) RunAndReturn(run func(context.Context, string) error) *MockUserConfirmationRepository_ConfirmUserRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserConfirmation provides a mock function with given fields: ctx, userID, token, expiresAt
func (_m *MockUserConfirmationRepository) CreateUserConfirmation(ctx context.Context, userID string, token string, expiresAt time.Time) (*domain.UserConfirmation, error) {
	ret := _m.Called(ctx, userID, token, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserConfirmation")
	}

	var r0 *domain.UserConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserConfirmation, error)); ok {
		return rf(ctx, userID, token, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserConfirmation); ok {
		r0 = rf(ctx, userID, token, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConfirmation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, userID, token, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConfirmationRepository_CreateUserConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserConfirmation'
type MockUserConfirmationRepository_CreateUserConfirmation_Call struct {
	*mock.Call
}

// CreateUserConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - token string
//   - expiresAt time.Time
func (_e *MockUserConfirmationRepository_Expecter) CreateUserConfirmation(ctx interface{}, userID interface{}, token interface{}, expiresAt interface{}) *MockUserConfirmationRepository_CreateUserConfirmation_Call {
	return &MockUserConfirmationRepository_CreateUserConfirmation_Call{Call: _e.mock.On("CreateUserConfirmation", ctx, userID, token, expiresAt)}
}

func (_c *MockUserConfirmationRepository_CreateUserConfirmation_Call) Run(run func(ctx context.Context, userID string, token string, expiresAt time.Time)) *MockUserConfirmationRepository_CreateUserConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockUserConfirmationRepository_CreateUserConfirmation_Call) Return(_a0 *domain.UserConfirmation, _a1 error) *MockUserConfirmationRepository_CreateUserConfirmation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConfirmationRepository_CreateUserConfirmation_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (*domain.UserConfirmation, error)) *MockUserConfirmationRepository_CreateUserConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserConfirmation provides a mock function with given fields: ctx, userID
func (_m *MockUserConfirmationRepository) DeleteUserConfirmation(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserConfirmationRepository_DeleteUserConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserConfirmation'
type MockUserConfirmationRepository_DeleteUserConfirmation_Call struct {
	*mock.Call
}

// DeleteUserConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserConfirmationRepository_Expecter) DeleteUserConfirmation(ctx interface{}, userID interface{}) *MockUserConfirmationRepository_DeleteUserConfirmation_Call {
	return &MockUserConfirmationRepository_DeleteUserConfirmation_Call{Call: _e.mock.On("DeleteUserConfirmation", ctx, userID)}
}

func (_c *MockUserConfirmationRepository_DeleteUserConfirmation_Call) Run(run func(ctx context.Context, userID string)) *MockUserConfirmationRepository_DeleteUserConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserConfirmationRepository_DeleteUserConfirmation_Call) Return(_a0 error) *MockUserConfirmationRepository_DeleteUserConfirmation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserConfirmationRepository_DeleteUserConfirmation_Call) RunAndReturn(run func(context.Context, string) error) *MockUserConfirmationRepository_DeleteUserConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserConfirmationByToken provides a mock function with given fields: ctx, token
func (_m *MockUserConfirmationRepository) GetUserConfirmationByToken(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserConfirmationByToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConfirmationRepository_GetUserConfirmationByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserConfirmationByToken'
type MockUserConfirmationRepository_GetUserConfirmationByToken_Call struct {
	*mock.Call
}

// GetUserConfirmationByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserConfirmationRepository_Expecter) GetUserConfirmationByToken(ctx interface{}, token interface{}) *MockUserConfirmationRepository_GetUserConfirmationByToken_Call {
	return &MockUserConfirmationRepository_GetUserConfirmationByToken_Call{Call: _e.mock.On("GetUserConfirmationByToken", ctx, token)}
}

func (_c *MockUserConfirmationRepository_GetUserConfirmationByToken_Call) Run(run func(ctx context.Context, token string)) *MockUserConfirmationRepository_GetUserConfirmationByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserConfirmationRepository_GetUserConfirmationByToken_Call) Return(_a0 string, _a1 error) *MockUserConfirmationRepository_GetUserConfirmationByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConfirmationRepository_GetUserConfirmationByToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUserConfirmationRepository_GetUserConfirmationByToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserConfirmationRepository creates a new instance of MockUserConfirmationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserConfirmationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserConfirmationRepository {
	mock := &MockUserConfirmationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
