// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEncryptionService is an autogenerated mock type for the EncryptionService type
type MockEncryptionService struct {
	mock.Mock
}

type MockEncryptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryptionService) EXPECT() *MockEncryptionService_Expecter {
	return &MockEncryptionService_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: ctx, encryptedText
func (_m *MockEncryptionService) Decrypt(ctx context.Context, encryptedText string) (string, error) {
	ret := _m.Called(ctx, encryptedText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, encryptedText)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, encryptedText)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, encryptedText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncryptionService_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockEncryptionService_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - encryptedText string
func (_e *MockEncryptionService_Expecter) Decrypt(ctx interface{}, encryptedText interface{}) *MockEncryptionService_Decrypt_Call {
	return &MockEncryptionService_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, encryptedText)}
}

func (_c *MockEncryptionService_Decrypt_Call) Run(run func(ctx context.Context, encryptedText string)) *MockEncryptionService_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEncryptionService_Decrypt_Call) Return(_a0 string, _a1 error) *MockEncryptionService_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncryptionService_Decrypt_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockEncryptionService_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: ctx, textToEncrypt
func (_m *MockEncryptionService) Encrypt(ctx context.Context, textToEncrypt string) (string, error) {
	ret := _m.Called(ctx, textToEncrypt)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, textToEncrypt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, textToEncrypt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, textToEncrypt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncryptionService_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncryptionService_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - textToEncrypt string
func (_e *MockEncryptionService_Expecter) Encrypt(ctx interface{}, textToEncrypt interface{}) *MockEncryptionService_Encrypt_Call {
	return &MockEncryptionService_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, textToEncrypt)}
}

func (_c *MockEncryptionService_Encrypt_Call) Run(run func(ctx context.Context, textToEncrypt string)) *MockEncryptionService_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEncryptionService_Encrypt_Call) Return(_a0 string, _a1 error) *MockEncryptionService_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncryptionService_Encrypt_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockEncryptionService_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEncryptionService creates a new instance of MockEncryptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryptionService {
	mock := &MockEncryptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
