// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIMailConfig is an autogenerated mock type for the IMailConfig type
type MockIMailConfig struct {
	mock.Mock
}

type MockIMailConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMailConfig) EXPECT() *MockIMailConfig_Expecter {
	return &MockIMailConfig_Expecter{mock: &_m.Mock}
}

// ConfirmationURLFormat provides a mock function with no fields
func (_m *MockIMailConfig) ConfirmationURLFormat() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfirmationURLFormat")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIMailConfig_ConfirmationURLFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmationURLFormat'
type MockIMailConfig_ConfirmationURLFormat_Call struct {
	*mock.Call
}

// ConfirmationURLFormat is a helper method to define mock.On call
func (_e *MockIMailConfig_Expecter) ConfirmationURLFormat() *MockIMailConfig_ConfirmationURLFormat_Call {
	return &MockIMailConfig_ConfirmationURLFormat_Call{Call: _e.mock.On("ConfirmationURLFormat")}
}

func (_c *MockIMailConfig_ConfirmationURLFormat_Call) Run(run func()) *MockIMailConfig_ConfirmationURLFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMailConfig_ConfirmationURLFormat_Call) Return(_a0 string) *MockIMailConfig_ConfirmationURLFormat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMailConfig_ConfirmationURLFormat_Call) RunAndReturn(run func() string) *MockIMailConfig_ConfirmationURLFormat_Call {
	_c.Call.Return(run)
	return _c
}

// MailFrom provides a mock function with no fields
func (_m *MockIMailConfig) MailFrom() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MailFrom")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIMailConfig_MailFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MailFrom'
type MockIMailConfig_MailFrom_Call struct {
	*mock.Call
}

// MailFrom is a helper method to define mock.On call
func (_e *MockIMailConfig_Expecter) MailFrom() *MockIMailConfig_MailFrom_Call {
	return &MockIMailConfig_MailFrom_Call{Call: _e.mock.On("MailFrom")}
}

func (_c *MockIMailConfig_MailFrom_Call) Run(run func()) *MockIMailConfig_MailFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMailConfig_MailFrom_Call) Return(_a0 string) *MockIMailConfig_MailFrom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMailConfig_MailFrom_Call) RunAndReturn(run func() string) *MockIMailConfig_MailFrom_Call {
	_c.Call.Return(run)
	return _c
}

// MailFromName provides a mock function with no fields
func (_m *MockIMailConfig) MailFromName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MailFromName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIMailConfig_MailFromName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MailFromName'
type MockIMailConfig_MailFromName_Call struct {
	*mock.Call
}

// MailFromName is a helper method to define mock.On call
func (_e *MockIMailConfig_Expecter) MailFromName() *MockIMailConfig_MailFromName_Call {
	return &MockIMailConfig_MailFromName_Call{Call: _e.mock.On("MailFromName")}
}

func (_c *MockIMailConfig_MailFromName_Call) Run(run func()) *MockIMailConfig_MailFromName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMailConfig_MailFromName_Call) Return(_a0 string) *MockIMailConfig_MailFromName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMailConfig_MailFromName_Call) RunAndReturn(run func() string) *MockIMailConfig_MailFromName_Call {
	_c.Call.Return(run)
	return _c
}

// SMTPHost provides a mock function with no fields
func (_m *MockIMailConfig) SMTPHost() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SMTPHost")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIMailConfig_SMTPHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SMTPHost'
type MockIMailConfig_SMTPHost_Call struct {
	*mock.Call
}

// SMTPHost is a helper method to define mock.On call
func (_e *MockIMailConfig_Expecter) SMTPHost() *MockIMailConfig_SMTPHost_Call {
	return &MockIMailConfig_SMTPHost_Call{Call: _e.mock.On("SMTPHost")}
}

func (_c *MockIMailConfig_SMTPHost_Call) Run(run func()) *MockIMailConfig_SMTPHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMailConfig_SMTPHost_Call) Return(_a0 string) *MockIMailConfig_SMTPHost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMailConfig_SMTPHost_Call) RunAndReturn(run func() string) *MockIMailConfig_SMTPHost_Call {
	_c.Call.Return(run)
	return _c
}

// SMTPPassword provides a mock function with no fields
func (_m *MockIMailConfig) SMTPPassword() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SMTPPassword")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIMailConfig_SMTPPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SMTPPassword'
type MockIMailConfig_SMTPPassword_Call struct {
	*mock.Call
}

// SMTPPassword is a helper method to define mock.On call
func (_e *MockIMailConfig_Expecter) SMTPPassword() *MockIMailConfig_SMTPPassword_Call {
	return &MockIMailConfig_SMTPPassword_Call{Call: _e.mock.On("SMTPPassword")}
}

func (_c *MockIMailConfig_SMTPPassword_Call) Run(run func()) *MockIMailConfig_SMTPPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMailConfig_SMTPPassword_Call) Return(_a0 string) *MockIMailConfig_SMTPPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMailConfig_SMTPPassword_Call) RunAndReturn(run func() string) *MockIMailConfig_SMTPPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SMTPPort provides a mock function with no fields
func (_m *MockIMailConfig) SMTPPort() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SMTPPort")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockIMailConfig_SMTPPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SMTPPort'
type MockIMailConfig_SMTPPort_Call struct {
	*mock.Call
}

// SMTPPort is a helper method to define mock.On call
func (_e *MockIMailConfig_Expecter) SMTPPort() *MockIMailConfig_SMTPPort_Call {
	return &MockIMailConfig_SMTPPort_Call{Call: _e.mock.On("SMTPPort")}
}

func (_c *MockIMailConfig_SMTPPort_Call) Run(run func()) *MockIMailConfig_SMTPPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMailConfig_SMTPPort_Call) Return(_a0 int) *MockIMailConfig_SMTPPort_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMailConfig_SMTPPort_Call) RunAndReturn(run func() int) *MockIMailConfig_SMTPPort_Call {
	_c.Call.Return(run)
	return _c
}

// SMTPUsername provides a mock function with no fields
func (_m *MockIMailConfig) SMTPUsername() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SMTPUsername")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIMailConfig_SMTPUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SMTPUsername'
type MockIMailConfig_SMTPUsername_Call struct {
	*mock.Call
}

// SMTPUsername is a helper method to define mock.On call
func (_e *MockIMailConfig_Expecter) SMTPUsername() *MockIMailConfig_SMTPUsername_Call {
	return &MockIMailConfig_SMTPUsername_Call{Call: _e.mock.On("SMTPUsername")}
}

func (_c *MockIMailConfig_SMTPUsername_Call) Run(run func()) *MockIMailConfig_SMTPUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMailConfig_SMTPUsername_Call) Return(_a0 string) *MockIMailConfig_SMTPUsername_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMailConfig_SMTPUsername_Call) RunAndReturn(run func() string) *MockIMailConfig_SMTPUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMailConfig creates a new instance of MockIMailConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMailConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMailConfig {
	mock := &MockIMailConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
