version: '3.8'

services:
  postgres_db:
    image: postgres:14
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: mailpit/mailpit
    ports:
      - "1025:1025"
      - "8080:8080"
    volumes:
      - mailpit-data:/var/lib/mailpit

volumes:
  postgres_data:
  mailpit-data:
