// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type RegistrationPending struct {
	ID            string
	Email         string
	Code          string
	CodeExpiresAt time.Time
	CreatedAt     *time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Locale       string
	Timezone     string
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
}
