// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRegistrationPending(ctx context.Context, arg CreateRegistrationPendingParams) (RegistrationPending, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRegistrationPending(ctx context.Context, id string) error
	DeleteRegistrationPendingByEmail(ctx context.Context, email string) error
	DeleteUser(ctx context.Context, id string) error
	GetRegistrationPending(ctx context.Context, id string) (RegistrationPending, error)
	GetRegistrationPendingByEmail(ctx context.Context, email string) (RegistrationPending, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
