// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_pending.sql

package sqlc

import (
	"context"
	"time"
)

const createRegistrationPending = `-- name: CreateRegistrationPending :one
INSERT INTO registration_pending(email, code, code_expires_at)
VALUES ($1::TEXT, $2::TEXT, $3::TIMESTAMP)
RETURNING id, email, code, code_expires_at, created_at
`

type CreateRegistrationPendingParams struct {
	Email         string
	Code          string
	CodeExpiresAt time.Time
}

func (q *Queries) CreateRegistrationPending(ctx context.Context, arg CreateRegistrationPendingParams) (RegistrationPending, error) {
	row := q.db.QueryRow(ctx, createRegistrationPending, arg.Email, arg.Code, arg.CodeExpiresAt)
	var i RegistrationPending
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRegistrationPending = `-- name: DeleteRegistrationPending :exec
DELETE FROM registration_pending
WHERE id = $1::TEXT
`

func (q *Queries) DeleteRegistrationPending(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRegistrationPending, id)
	return err
}

const deleteRegistrationPendingByEmail = `-- name: DeleteRegistrationPendingByEmail :exec
DELETE FROM registration_pending
WHERE email = $1::TEXT
`

func (q *Queries) DeleteRegistrationPendingByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteRegistrationPendingByEmail, email)
	return err
}

const getRegistrationPending = `-- name: GetRegistrationPending :one
SELECT id,
       email,
       code,
       code_expires_at,
       created_at
FROM registration_pending
WHERE id = $1::TEXT
LIMIT 1
`

func (q *Queries) GetRegistrationPending(ctx context.Context, id string) (RegistrationPending, error) {
	row := q.db.QueryRow(ctx, getRegistrationPending, id)
	var i RegistrationPending
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRegistrationPendingByEmail = `-- name: GetRegistrationPendingByEmail :one
SELECT id, email, code, code_expires_at, created_at
FROM registration_pending
WHERE email = $1::TEXT
LIMIT 1
`

func (q *Queries) GetRegistrationPendingByEmail(ctx context.Context, email string) (RegistrationPending, error) {
	row := q.db.QueryRow(ctx, getRegistrationPendingByEmail, email)
	var i RegistrationPending
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.CodeExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
