// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(email, password_hash)
     VALUES ($1::TEXT, $2::BYTEA)
  RETURNING id, email, password_hash, first_name, last_name, locale, timezone, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1::TEXT
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id,
       email,
       password_hash,
       first_name,
       last_name,
       locale,
       timezone,
       created_at,
       updated_at,
       deleted_at
FROM users
WHERE id = $1::TEXT
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, locale, timezone, created_at, updated_at, deleted_at
  FROM users
 WHERE email = $1::TEXT
   AND deleted_at is NULL
 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
  SELECT id,
         email,
         password_hash,
         first_name,
         last_name,
         locale,
         timezone,
         created_at,
         updated_at,
         deleted_at
    FROM users
   WHERE ($1::TEXT IS NULL OR email = $1)
     AND ($2::TIMESTAMP IS NULL OR created_at >= $2::TIMESTAMP)
     AND ($3::TIMESTAMP IS NULL OR created_at <= $3::TIMESTAMP)
     AND (deleted_at is null) = $4::BOOLEAN
`

type ListUsersParams struct {
	Email             *string
	CreatedStartRange *time.Time
	CreatedEndRange   *time.Time
	Active            bool
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Email,
		arg.CreatedStartRange,
		arg.CreatedEndRange,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Locale,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $1::BYTEA,
    updated_at = now()
WHERE id = $2::TEXT
`

type UpdatePasswordParams struct {
	Passwordhash []byte
	Userid       string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Passwordhash, arg.Userid)
	return err
}

const updateUser = `-- name: UpdateUser :one
    UPDATE users
       SET email         = $1::TEXT,
           password_hash = $2::BYTEA,
           first_name    = $3::TEXT,
           last_name     = $4::TEXT,
           locale        = $5::TEXT,
           timezone      = $6::TEXT,
           updated_at    = now()
     WHERE id = $7::TEXT
 RETURNING id, email, password_hash, first_name, last_name, locale, timezone, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Locale       string
	Timezone     string
	ID           string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Locale,
		arg.Timezone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
